### ISSUE TITLE
Problems with recent versions of projen

### ISSUE THREAD

**Issue by rlmartin** [terraform-cdk-providers/cdktf-provider-project#55]
Hello,

I have been trying to spin up my own `cdktf-provider-*` repo - specifically for the [PagerDuty Terraform provider](https://registry.terraform.io/providers/PagerDuty/pagerduty/latest). I followed the [instructions](https://github.com/terraform-cdk-providers/cdktf-provider-project#creating-a-new-provider) and was ultimately able to get it to work, but versions of `projen` beyond `0.3.38` are overwriting the version in `package.json` with `[Object object]`. This breaks the build unless the project is pinned to `0.3.38` via `yarn.lock`. To get around this I had to:

* `npm install @cdktf/provider-project@latest`
* `npx projen@0.3.38`
* `chmod +w package.json`
* Edit `package.json`'s `projen` version from `^0.3.38` to `0.3.38`
* `yarn install`
* Edit `yarn.lock`'s `projen` version from `0.3.38` to `^0.3.38`
* Edit back `package.json`'s `projen` version from `0.3.38` to `^0.3.38`
* `chmod -w package.json`

I think it is coincidental that the existing provider projects are building successfully - it is only because `yarn` locked the version and is using that old version.

**Comment by skorfmann** [comment]
Thanks for raising this issue. I can confirm, that this should be addressed. I think the support for 3rd party packages got improved quite a bit in recent versions of projen. As part of upgrading projen, I'd hope that these kind of problems would go away entirely.

**Comment by rlmartin** [comment]
I didn't play much with different versions of `projen` but I had issues with both latest (`0.15.13`) and the latest in the minor version (`0.3.179`). I may have been using it wrong, but it seemed like maybe the usage or interface changed in some way.
