### ISSUE TITLE
DigitalOcean Provider support?

### ISSUE THREAD

**Issue by jubairsaidi** [terraform-cdk-providers/cdktf-provider-project#59]
Not sure the place to ask this, but any chance we can get a DO CDK provider?

**Comment by skorfmann** [comment]
Adding a pre-built Digital Ocean provider sounds like a good idea in general. In the meantime, you can build the provider [locally](https://github.com/hashicorp/terraform-cdk/blob/main/docs/working-with-cdk-for-terraform/using-providers-and-modules.md#importing-providers-and-modules)

**Comment by jubairsaidi** [comment]
Thanks!

Closing this one, it's a dup of https://github.com/hashicorp/terraform-cdk/issues/531#issuecomment-770290934
